server:
  #服务端口号 默认是8080
  port: 9001
spring:
  application:
    #服务名称
    name: consumer
eureka:
  client:
    #是否将自己注册到Eureka Server,默认为true，由于当前就是server，故而设置成false，表明该服务不会向eureka注册自己的信息
    register-with-eureka: true
    #是否从eureka server获取注册信息，由于单节点，不需要同步其他节点数据，用false
    fetch-registry: true
    #设置服务注册中心的URL，用于client和server端交流
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  server:
    #关闭自我保护机制
    enable-self-preservation: false

#provider:
#  ribbon:
#    #通过配置文件设置ribbon均衡策略
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#ribbon:
#  eureka:
#  #Ribbon脱离Rureka 自己选择服务，不通过Rureka拉取服务列表
#    enabled: false
#  listOfServers: localhost:8001

