spring:
  application:
    name: config-demo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lyk19941022/SpringCloud-Config-Demo.git
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
server:
  port: 9999